FROM node:lts-hydrogen

RUN apt-get update && apt-get install -y \
    mariadb-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/node/moon-apps
WORKDIR /home/node/moon-apps

COPY package*.json ./

RUN npm install

COPY . .

ADD https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD /wait-for-it.sh mariadb:3306 -- npx prisma migrate deploy && npm run build