FROM node:lts-hydrogen

RUN apt-get update && apt-get install -y \
    mariadb-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER node

RUN mkdir -p /home/node/moon-apps
WORKDIR /home/node/moon-apps

RUN npm install && npm run build