version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.prod
    container_name: moon-apps-app
    depends_on:
      - mariadb
    command: [ "/bin/bash", "-c", "exec /bin/bash" ]
    tty: true
    volumes:
      - ..:/home/node/moon-apps
    ports:
      - "3300:3000"
    restart: unless-stopped

  mariadb:
    image: mariadb:lts-jammy
    container_name: moon-apps-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ../mariadb/storage:/var/lib/mysql
      - ../mariadb/config:/etc/mysql
      - ../mariadb/logs:/var/log/mysql
      - ./prod_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

networks:
  default:
    driver: bridge
