CREATE DATABASE IF NOT EXISTS moon;
GRANT ALL PRIVILEGES ON moon.* TO 'maria'@'%';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS moonshadow;
GRANT ALL PRIVILEGES ON moonshadow.* TO 'maria'@'%';
FLUSH PRIVILEGES;